export const navItems = [
  { name: "About", scrollTo: "about" },
  { name: "Skills", scrollTo: "skills" },
  { name: "Projects", scrollTo: "projects" },
  { name: "Experience", scrollTo: "experience" },
  { name: "Contact", scrollTo: "contact" },
];

export const skillsData = [
  {
    category: "Frontend Development",
    skills: [
      { name: "React.js", rating: 8 },
      { name: "React Native", rating: 7 },
      { name: "JavaScript", rating: 8 },
      { name: "HTML/CSS", rating: 9 },
      { name: "Tailwind CSS", rating: 8 },
    ],
  },
  {
    category: "Backend Development",
    skills: [
      { name: "Node.js", rating: 6 },
      { name: "PHP", rating: 5 },
      { name: "Java", rating: 5 },
      { name: "C++", rating: 6 },
      { name: "REST API", rating: 6 },
    ],
  },
  {
    category: "Database & Cloud",
    skills: [
      { name: "Firebase", rating: 8 },
      { name: "SQL", rating: 8 },
      { name: "PL/SQL", rating: 4 },
      { name: "NoSQL", rating: 8 },
      { name: "Docker", rating: 5 },
    ],
  },
  {
    category: "Design & Tools",
    skills: [
      { name: "Figma", rating: 9 },
      { name: "Git", rating: 7 },
      { name: "Power BI", rating: 7 },
      { name: "Video Editing", rating: 6 },
      { name: "UI/UX Design", rating: 8 },
    ],
  },
];

export const projectsData = [
  {
    id: 0,
    title: "TenancyPilot",
    subtitle: "Full-stack property management SaaS platform for landlords and property managers to streamline tenant management, rent collection, and property maintenance.",
    category: "Web App",
    tags: "SaaS | Property Management | Full-Stack",
    year: "September 2024",
    month: "Sep",
    status: "Deployed",
    users: "200+ active users",
    websiteUrl: "https://tenancypilot.com",
    techStack: ["Next.js", "TypeScript", "Tailwind CSS", "shadcn/ui", "PostgreSQL", "Prisma", "Supabase"],
    lightImages: [
      "/projectImages/tenancypilotlaptopview.png",
    ],
    darkImages: [
      "/projectImages/tenancypilotlaptopview(Dark).png",
    ],
    viewingImagesLight: "/projectImages/tenancypilotmain.png",
    viewingImagesDark: "/projectImages/tenancypilotmain.png",
    description: "TenancyPilot is a comprehensive property management platform that simplifies landlord-tenant relationships through automated rent collection, maintenance tracking, and document management.",
    bgColor: "var(--color-purple-dark)",
    textColor: "--color-purple-dark",
  },
  {
    id: 1,
    title: "Leafloat Restaurant POS",
    subtitle: "Complete point-of-sale system for restaurants with real-time order management, inventory tracking, and sales analytics.",
    category: "Web App",
    tags: "POS | Restaurant | Full-Stack",
    year: "October 2024",
    month: "Oct",
    status: "In Development",
    users: "Frontend demo ready",
    websiteUrl: null,
    techStack: ["React.js", "TypeScript", "Tailwind CSS", "TanStack Query", "TanStack Router", "shadcn/ui", "PostgreSQL", "Supabase"],
    lightImages: [
      "/projectImages/posview.png",
    ],
    darkImages: [
      "/projectImages/posview(dark).png",
    ],
    viewingImagesLight: "/projectImages/posmain.png",
    viewingImagesDark: "/projectImages/posmain.png",
    description: "Leafloat Restaurant POS is a modern point-of-sale system designed for restaurants, featuring intuitive order management, kitchen display integration, and comprehensive sales reporting.",
    bgColor: "linear-gradient(to bottom right, var(--color-blue-primary), var(--color-blue-dark))",
    textColor: "--color-blue-primary",
  },
  {
    id: 2,
    title: "LumeaAI",
    subtitle: "Design and development of the LumeaAI web application, showcasing structured, user-friendly user interface for real-time employee behavior monitoring, productivity analytics, and intuitive navigation across core system features.",
    category: "Web App",
    tags: "WebApp | Dashboard | Analytics",
    year: "2024 - 2025",
    month: "2024",
    status: "Completed",
    users: null,
    websiteUrl: null,
    techStack: ["React.js", "Firebase", "Firestore"],
    lightImages: [
      "/projectImages/LumeaAILight.png",
      "/projectImages/LumeaAILightTablet.png",
      "/projectImages/LumeaAILightPhone.png",
    ],
    darkImages: [
      "/projectImages/LumeaAIDark.png",
      "/projectImages/LumeaAIDarkTablet.png",
      "/projectImages/LumeaAIDarkPhone.png",
    ],
    viewingImagesLight: "/projectImages/LumeaAIDarkMain.png",
    viewingImagesDark: "/projectImages/LumeaAIDarkMain.png",
    description: "LumeaAI is an innovative staff productivity monitoring platform developed to help organizations gain real-time insights into employee behavior using AI-powered camera systems.",
    customerProblem: "Many workplaces struggle with gaining accurate, timely insights into employee activity and behavior. Traditional methods of supervision are either invasive, inefficient, or lack actionable data — leading to blind spots in performance management and decision-making.",
    solution: "LumeaAI was developed as a forward-thinking solution to this challenge. By combining computer vision with intelligent data visualization, the platform enables organizations to monitor productivity trends, detect key behaviors, and make informed decisions — all through a seamless web interface.",
    result: "The result is a responsive and functional web application that enables organizations to monitor staff behavior in real time and gain actionable productivity insights.",
    bgColor: "var(--color-purple-dark)",
    textColor: "--color-purple-dark",
  },
  {
    id: 3,
    title: "uFound",
    subtitle: "Campus-focused lost and found platform with real-time item reporting, secure claim processing, and smart filtering for students and staff.",
    category: "Web App",
    tags: "WebApp | Lost and Found",
    year: "2024",
    month: "2024",
    status: "Completed",
    users: null,
    websiteUrl: null,
    githubUrl: "https://github.com/placeholder",
    techStack: ["React.js", "Node.js", "MySQL", "MariaDB"],
    lightImages: [
      "/projectImages/LAndFSystemLight.png",
      "/projectImages/LAndFSystemLightTablet.png",
      "/projectImages/LAndFSystemLightPhone.png",
    ],
    darkImages: [
      "/projectImages/LAndFSystemDark.png",
      "/projectImages/LAndFSystemDarkTablet.png",
      "/projectImages/LAndFSystemDarkPhone.png",
    ],
    viewingImagesLight: "/projectImages/LAndFSystemMain.png",
    viewingImagesDark: "/projectImages/LAndFSystemMain.png",
    description: "uFound is a digital lost and found management system developed as my final year project at Universiti Teknikal Malaysia Melaka (UTeM). It was designed to streamline how students and staff report, track, and recover lost items on campus.",
    customerProblem: "Students and staff often lose personal items on campus, but the lack of a structured, accessible system makes it difficult to report, track, and recover them efficiently.",
    solution: "uFound provides a centralized digital platform that allows users to easily report, track, and claim lost or found items within the university campus.",
    result: "The uFound system was successfully developed and demonstrated as a final year project at UTeM, where it was well received by academic supervisors.",
    bgColor: "linear-gradient(to bottom right, var(--color-blue-primary), var(--color-blue-dark))",
    textColor: "--color-blue-primary",
  },
  {
    id: 4,
    title: "Super Admin Dashboard",
    subtitle: "Web-based Super Admin platform for centralized management of organizations, applications, subscription plans, and customer deals within the Datalytica ecosystem.",
    category: "Web App",
    tags: "Web | Dashboard | Admin",
    year: "2025",
    month: "2025",
    status: "Completed",
    users: null,
    websiteUrl: null,
    techStack: ["React.js", "Firebase", "Firestore"],
    lightImages: [
      "/projectImages/SuperAdminLight.png",
      "/projectImages/SuperAdminLightTablet.png",
      "/projectImages/SuperAdminLightPhone.png",
    ],
    darkImages: [
      "/projectImages/SuperAdminDark.png",
      "/projectImages/SuperAdminDarkTablet.png",
      "/projectImages/SuperAdminDarkPhone.png",
    ],
    viewingImagesLight: "/projectImages/SuperAdminMain.png",
    viewingImagesDark: "/projectImages/SuperAdminMain.png",
    description: "The Super Admin System is a centralized web platform for managing organizations, products, subscription plans, and deals within the Datalytica ecosystem.",
    customerProblem: "As the Datalytica ecosystem began to grow, there was a need for a unified platform to manage their clients and products they are subscribed to efficiently.",
    solution: "The Super Admin System was developed to provide a centralized platform where Datalytica can efficiently manage its organizations, assign products, configure subscription plans, and handle deals.",
    result: "The Super Admin System successfully streamlined core management tasks across the Datalytica ecosystem, establishing a solid foundation for future scalability.",
    bgColor: "var(--color-purple-dark)",
    textColor: "--color-purple-dark",
  },
];

export const workExperienceData = [
  {
    id: 0,
    company: "Leafloat Robotics",
    role: "Software Engineer (Contract)",
    period: "October 2025 - Present",
    location: "Selangor, Malaysia",
    website: "https://leafloat.tech",
    description: [
      "Building a full-featured restaurant POS with React 19, TypeScript, and TanStack Router/Query/Store, handling order flows, menu management with combo builders, add-ons, discounts, and a kanban-style kitchen display. In addition to the management of staff and subscribers.",
      "Architected the project from initial planning through system design, frontend structure, and database schema.",
      "Currently under development; frontend mostly complete, backend integration in progress after finalizing the database schema."
    ],
    techStack: ["React.js", "TypeScript", "TanStack Router", "TanStack Query", "TanStack Store", "Tailwind CSS", "shadcn/ui", "Figma"],
  },
  {
    id: 1,
    company: "Ezyfusion Group Sdn Bhd",
    role: "Software Engineer (Contract)",
    period: "September 2025 - Present",
    location: "Melaka, Malaysia",
    website: null,
    description: [
      "Built the whole project from scratch, handling the system design, backend, database, and frontend.",
      "Built tenant and staff portals with role-based access control, lease management, automated rental payment generation, recurring payment generation, notification system using pg_cron scheduling and others.",
      "Integrated Billplz payment gateway enabling 200+ tenants to pay rent and other payments online, currently live and actively used by a property management company with ongoing feature development.",
    ],
    techStack: ["Next.js", "TypeScript", "Supabase", "Prisma", "Tailwind CSS", "shadcn/ui", "Figma"],
  },
  {
    id: 2,
    company: "Datalytica Sdn Bhd",
    role: "Frontend Developer (Internship)",
    period: "October 2024 - April 2025",
    location: "Kuala Lumpur, Malaysia",
    website: "https://datalytic.ai/",
    description: [
      "Redesigned and optimized an AI productivity monitoring web app using React.js and Firebase, improving performance and reducing costs by +50% through optimized resource usage.",
      "Built internal admin portal for managing organizations, and subscriptions.",
      "Designed UI/UX interfaces across multiple products using Figma, improving usability and platform consistency.",
    ],
    techStack: ["React.js", "Firebase", "Power BI", "Figma"],
  },
];

export const educationData = [
  {
    id: 0,
    institution: "Universiti Teknikal Malaysia Melaka (UTeM)",
    degree: "Bachelor of Computer Science (Software Engineering) with Honours",
    period: "October 2021 - April 2025",
    location: "Melaka, Malaysia",
    cgpa: "3.41/4.00",
    highlights: [
      "Final Year Project: uFound - Campus Lost and Found Management System.",
      "Workshop 2 Project: Veterinary Management System."
    ],
  },
];
